Algorithms/Divide and Conquer/binary-search.php
As the algorithm divide and conquer is also applied to algorithms that reduce each problem to only one sub-problem, the binary search algorithm is considered as a divide and conquer algorithm. 
In a binary search, the search space is reduced in each step where the sub-problem is of roughly half the original size. The binary search is also called decrease and conquer algorithm as search space is reduced in each step. In a binary search, the sub-problem can be solved using iterative or recursive approaches. Following is the iterative approach for solving binary search in PHP
=> Binary search in PHP using divide and conquer algorithm

Algorithms/Mathematical Algorithms/factorial.php
What is a factorial?
The factorial function (symbol: !) says to multiply all whole numbers from our chosen number down to 1.
=> PHP code to find a factorial of a number.

Algorithms/Divide and Conquer/quicksort.php
The algorithm picks a pivot element, rearranges the array elements in such a way that all elements smaller than the picked pivot element move to left side of pivot, and all greater elements move to right side. Finally, the algorithm recursively sorts the subarrays on left and right of pivot element.
=> Quick Sort in PHP

Algorithms/Insertionsort/insertion_sort.c
Insertion sort implemented in C language
=> insertion sort in c

Algorithms/Mathematical Algorithms/gcd.py
added gcd finding algorithm in algorithms -> Mathematical ALgorithms folder
=> Greatest Common Divisor algorithm

Algorithms/Sorting/InsertionSort/insertionSort.cpp
=> Algorithm for Insertion Sort in C++ added

Algorithms/Graph Theory/depth_first_search.py
Creating the DFS algorithm in python along with a dummy graph for testing purposes
=> DFS implementation in python

Algorithms/Divide and Conquer/Maximum Subarray Sum
this program uses divide and conquer strategy to solve the maximum subarray sum problem. Here the time complexity is O(nLogn).
=> Maximum Subarray Sum

Algorithms/Divide and Conquer/mergesort.php, Algorithms/Mathematical Algorithms/fibonacci.php
It gives a series of numbers in which each number ( Fibonacci number ) is the sum of the two preceding numbers. The simplest is the series 1, 1, 2, 3, 5, 8, etc.
=> Fibonnaci Series in PHP

Algorithms/Max_Sum_Pair/MaxSumPair.py
Create a simple way to add the two largest elements in an array and add them in python.
=> Finding the pair of elements in an array with maximum sum in python

Data Structures/Binary Tree/binary_tree.cpp
Binary Tree implementation in cpp added
=> Binary Tree

insertion_sort.cpp
to use std::cout/endl/cin is important that you include iostream
=> Include "iostream"

Algorithms/Djkstra/code.cpp, Algorithms/DynamicProgramming/KnapsackProblem/cubo.cpp, Data Structures/LinkedLists/repMusic.cpp
A C++ code that simulates a music player using linked lists.
=> Music Player

Algorithms/Mathematical Algorithms/factorial.py, Algorithms/Power of Two/is_power_of_two.py
Script requires at least one integer as argument in order to work properly.
Prints usage message and exits if no arguments are given.  
Also, displays error message in case the argument given is not an integer.
=> Python console script to test if arguments are a power of two

Algorithms/Power of Two/Golang/power_of_two.go
=> #57 - Add golang script which checks if a number is a power of two

Algorithms/HeapSort/HeapSort.cpp
Done working on heap sort algorithm.
File contains working algorithm + a check in int main()
=> Added heap sort algorithm

Graph Theory/DijkstraAlgorithm.java
Implementation of Dijkstra Algorithm #31 in java
=> Added Dijkstra Algorithm

Algorithms/Sorting/QuickSort.go
quicksort implementation in golang
=> QuickSort.go

Algorithms/Data Structures/Fenwick Tree/fenwick_tree.cpp, Algorithms/Data Structures/Trie/Trie.cpp
Added basic trie / fenwick tree implementation written in C++.
also added comments to explain what every bit of code does.
=> Trie data structure.

Algorithms/Graph_Theory/Dijkstra.cpp
Added Dijkstra algorithm written with C++
Used adjacency list as a data structure to store the edges
=> Added Dijkstra algorithm written with C++

Algorithms/Sorting/Heap/heap_sort.cpp, Algorithms/Sorting/Insertion/Insertion_sort.cpp
Added insertion sort code in sorting folder of Algorithm folder
=> Added insertin sort code in algorithm folder

Data Structures/BST/TreeTraversal.cpp
File that shows Binary Search Tree Traversal in C++.
=> Tree Traversal in C++

Data Structures/SegmentTrees/range min query.cpp, Data Structures/SegmentTrees/sum of a range.cpp
Added range minimum query and range sum codes for Segment Tree implemented in C++14!
=> Added range minimum query and range sum codes for Segment Tree

Algorithms/Power of Two/Java/Main.java
I used recursion to implement isPowerOfTwo in Java.
=> add java implementation of Power Of Two

Algorithms/Power of Two/power-of-two.rb
Created `power-of-two.rb`, a ruby script to check if a given number is a power of 2.
=> add power-of-two.rb

insertionSort.py
I added the insertionSort using the Python language.
=> Add insertionSort in Python

Algorithms/SpiralOrderTraversal.java
Created a program for spiral order or level order traversal in a binary tree in Java.
#58
=> added spiral order traversal for java

Algorithms/Sorting/MergeSort/mergesort_opt.cpp
An improved version of merge sort using STL and C++1x features as well as removing recursion
=> More optimized version of merge sort.

Algorithms/rsa..c
Implementation of  RSA algorithm in C
=> Implementation of  RSA algorithm in C

Algorithms/Mathematical Algorithms/fibonacci.cpp
A non-recursive implementation of fibonacci in C++.
=> Non-recursive fibonacci implementation in C++.

Algorithms/Mathematical Algorithms/sumofmultiplesof3and5.hs
Associated Issue: #101 
###Summary of Changes:
- Added Haskell solution for the [Algorithms/Mathematical Algorithms](/Algorithms/Mathematical Algorithms) problem "Find sum of the multiples of 3 and 5 in [3,N)". My solution uses Haskell's built-in lazy lists to strictly sum all numbers that are multiples of 3 and 5, then subtracts the set of numbers which are both multiples of 3 and 5 (duplicates).
=> Added solution for sum of multiples of 3 and 5 under N

Algorithms/Mathematical Algorithms/GreatestCommonDenominator.cs
=> GCD implementation in C#.

Data Structures/Red Black Trees/Red_Black_Tree.cpp, Data Structures/Red Black Trees/Red_Black_Tree.h
Added implementation of red black trees on C++
=> Red Black Trees

Algorithms/Mathematical Algorithms/sumofmult3and5.js
=> add file for #101

Algorithms/RSA.java
=> Implementing RSA in Java

Algorithms/Mathematical Algorithms/3sand5s.cpp
C++ file summing the multiples of 3 and 5 below N.
=> Added file for #101,

Algorithms/Mathematical Algorithms/MultipleOfThreeAndFive.java
=> Add multiple of three and five in java

Algorithms/rsa.py
https://github.com/rathoresrikant/HacktoberFestContribute/issues/92
=> Add Rsa::python 3.6 to Algorithms

Algorithms/Sorting/Dutch_national_flag.cpp
A 3 way quick sort for array with repeating elements
#1
=> Dutch national flag algo added

Bit Manipulation/powerOf2.cpp
solution to check if a number can be written in power of 2 added. Please, merge this pr.
=> solution to power of 2 added.

Algorithms/DFS&BFS.CPP
Depth First Search & Breadth First Search program in C++
=> Depth First Search and Breadth First Search program in C++.

Algorithms/DynamicProgramming/KnapsackProblem/optimizedKnapSack.cpp
=> Added the space-optimized solution of KnapSack Problem

cousins_sum.cpp
this is an implementation of cousins sum problem in c++. feel free to give nay suggestion in solution. if it is wrong then please tell me. i will correct it.
=> added solution of cousins sum problem.

Algorithms/Mathematical Algorithms/Prime.cpp
Generates **_prime numbers_** upto a given _'N'_, using **_Sieve of Eratosthenes_** algorithm.
=> A basic prime number generator program

Algorithms/compute_nCk.cpp
first day on github;
fixed #152 
cheers
=> added: algorithm to compute nCk

Second Largest Element.cpp
=> adding code for computing second largest element in a given array

Algorithms/Mathematical Algorithms/sumofmultiplesof3and5.py
#101 added sum of multiples of 3 and 5 in python
=> Add sum of multiples of 3 and 5 in python

Algorithms/Sieve of Eratosthenes/sieve_of_eratosthenes.py
implemented a function allowing for calculating primaty numbers form 0 to given limit
=> 1 Add sieve of eratosthenes function python implementation

powerof2_ankit
>>c -program to find whether the number is power of two.
=> c- programing

creverse.c
we can reverse a linked list or can display it also or see whether we've successfully reversed it or not
=> reverse linked list

main.c
It's the first time i contribute in Github sorry if it not how it work
=> I did it in C.

Algorithms/Graph_Algorithms/Ford-Fulkerson-Algorithm.java
This is with reference to #167
=> Added Ford-Fulkerson-Algorithm in java

Algorithms/Search/binary_search.cpp
Kindly review my changes and add and merge my changes
=> Added implementation of BINARY_SEARCH in algorithms/search folder

Algorithms/vinay1.cpp
I have added implementation of Ford Fulkerson Algorithm in C++ in Algorithms Folder.
=> added implementation of Ford Fulkerson Algorithm in C++

Algorithms/Mathematical Algorithms/catalan_number.py
=> catalan_number.py

Algorithms/Mathematical Algorithms/PerfectNos.cpp
A simple cpp program to find the perfect nos between a given range of numbers.
=> Fix #184 : Created Perfect nos program

Algorithms/Sieve of Eratosthenes/sieve_of_eratosthenes.cpp
=> Added c++ implementation of Sieve of Eratosthenes

Algorithms/Mathematical Algorithms/armstrong_Number.cpp
A simple cpp program to check whether a three digit number is an Armstrong number or not.
=> Fix #180: Added armstrong_Number.cpp

Algorithms/Mathematical Algorithms/perfect_numbers.py
=> Generating perfect numbers (Python)

Algorithms/Mathematical Algorithms/MultipleOfThreeAndFive.java
=> changed algorithm to run in constant time

Algorithms/Array/array_reverse.php
Program to Print reverser of array without array_reverser function
=> Program to Print reverser of array

reverseLinkedList.cpp
Kindly review my reversing a linked list program and merge my changes
=> Added program to REVERSE a LINKED LIST in C++

Algorithms/Mathematical Algorithms/PerfectNumbers.py
Now User can provide input in the script rather than specific range 1 to 500, Ordering of input doesn't matter (either type Bigger number first or vice versa)
#184 
Updated the code.
=> #updated the code. Removed hard coded input(Range 1 to 500), Now user can provide Range in the code. Ordering Of Input doesn't matter.

Algorithms/Graph_Algorithms/fordfulkerson.py, Data Structures/LinkedLists/LinkedList.java
=> Intersection of 2 linked lists & Ford Fulkerson

interchangeLetterCase.cpp, removeAllSubstring.cpp
=> remove all substring from a string, interchange letter case

generateCatalanNo.cpp
Generating catalan number using O(n) approach.
=> Uploaded generateCatalanNo.cpp

Algorithms/SparseMatrix/SparseAddMultipl.cpp
Added Sparse matrix multiplication using a matrix of rows, columns and data.
=> Added Sparse Matrix Multiplication

string_case_invert.cpp
converting case from lower to upper and upper to lower of a string.
Written in C++.
Please merge the program.
=> inverting case of a string 

Graph Theory/max_flow.cpp
I have implemented the max flow min cut problem. Code is self explanatory.
=> code for max flow min cut problem

Geometry Algorithms/convex_hull.cpp
This is an implementation of convex hull algorithm. please look at it and suggest any modification.
=> Coded convex hull

string_permutation.cpp
Given program takes string as  an input and prints all permutations(ordering or arrangement) of a string using Stl.
=> Uploaded string_permutation.cpp

palindrome.cpp
Name: Vikas Goswami (https://github.com/con007/)
Place: Lucknow
About: Software Developer(Fresher)
Programming Language: C, C++, Python, HTML, CSS.
Email: vikaskv001@gmail.com
=> Added program to check string is palindrome or not

SringPermutation.java
Created a java file to find all the permutation of a string
=> Created StringPermutation.java file

Algorithms/DynamicProgramming/longest_common_subsequence.cpp
C++ code for Longest Common Sub-sequence.
=> Longest Common Sub-sequence

Data Structures/Bubble sort.txt, GITSECLA.CPP
Basically I converted the incompleted c++ program written in bubble_sort.txt file into the completed one.
=> Updated bubble_sort.txt

LargestSumConstiguous.cpp
=> Largest Sum Constiguous

Intersection.cpp
line 29 had an inappropriately formatted comment, it would have been mistaken for code
=> commented the comment

Graph Theory/floyd_warshall_algorithm.cpp
Added floyd warshall algorithm for finding all pair shortest path in an undirected weighted graph.
=> Added floyd warshall algorithm

first_non_repeating_char.py
[Issue# 266](https://github.com/rathoresrikant/HacktoberFestContribute/issues/266)
=> Added solution for issue#266

FirstNonRepeatingCharacter.py
This is simple one-liner which implements algorithm for finding first non-repeating character in a given string.
#266
=> Python implementation of algorithm, to find first non-repeating char.

Algorithms/CPU Scheduling/Round Robin.cpp
Added Round Robin CPU Scheduling Algorithm.
=> Added Round Robin Algo

Cryptography/extended_euclid_gcd.cpp
Extended Euclid Gcd is efficient way to evaluate inverse of number modulo n and plays a crucial role in cryptography.
=> Added Extended Eulid Gcd algorithm

Algorithms/Mathematical Algorithms/factorial.cpp, Algorithms/Mathematical Algorithms/greatest_common_divisor.cpp, calculator.c, string_after_deleting_vowel.cpp
A new file named "factorial.cpp" is added.
=> Adds factorial.cpp

Algorithms/firstNonRepeatingCharacter.ts
This pull request aims to add a function that finds the first non-repeating character in a string, this time written in TypeScript.
=> Add TypeScript solution – #266

remove_vowels_from_string.py
[Issue#282](https://github.com/rathoresrikant/HacktoberFestContribute/issues/282)
=> Solving issue#282

remove_extra_spaces_from_string.py
[Issue#313](https://github.com/rathoresrikant/HacktoberFestContribute/issues/313)
=> Solving issue#313

src/python/revove_extra_spaces.py
=> Closes: #313

src/python/remove_substring.py, src/python/revove_extra_spaces.py
=> Remove all the occurences of a substring of that string

remove_extra_space.py
fixes #313 
added py code to remove extra whitespace
Python
=> added py code to remove extra whitespace

Algorithms/Graph_Theory/A_star.cpp
Added a C++ implementation of the A* algorithm to the Algorithms/Graph-Theory folder.
=> A* Search Algorithm

remove-extra-spaces.py
Added a remove-extra-spaces.py file which can remove extra spaces from a string.
=> Added python code to remove extra spaces from a string

Algorithms/Graph_Algorithms/Lee's-Algorithm.cpp
Adding Lee's Algorithm, a breadth-first search based solution for maze routing problems, to the Algorithms/Graph-Algorithms folder
=> Lee's Algorithm

Backtracking/NQueen.cpp, infix2postfix.c
=> Added NQueen.cpp implementing the NQueens algorithm using both iterative and recursive approaches using C++ language

InterchangeLetterCase.java
=> Convert all the lowercase letters to upper case and vice versa - Java Solution

Data Structures/LinkedLists/LinkedListIntersection.java, remove-extra-spaces.py
Added a file LinkedListIntersection.java with a simple implementation of a LinkedList and a helping Node inner class.
Added a method `boolean intersection(LinkedListIntersection) { ... }` that can be used to check if two linked lists have at least one common node.
=> LinkedList intersection

Algorithms/Strings/Anagram.cs
Algorithm checking if first word is anagram of second one. Solution written in C#.
=> Solution for checking if word is anagram of second one written in C#

Algorithms/Greedy/Knight's_Tour.cpp
A knight's tour is a sequence of moves of a knight on a chessboard such that the knight visits every square only once. (C++ Greedy implementation)
=> Knight's Tour

LICENSE, commonChars.cpp
Get the identical chars in two strings and print them alphabetically.
=> Common chars

vinay4.py
I have added program in python to  Print the common characters of two strings in alphabetical order.
#346
=> added program in python

CommonLetters.js
This example rely on nodeJs, but the `intersect` function can be used on any scenario
=> add CommonLetters in Javascript. resolves #346

Algorithms/Array/Kadane's Algorithm
=> Kadane's Algorithm

case_shift.py
=> Case-swap chars in string python

fib.cpp
=> nth fibonacci value; recursive; cpp;

caseChangeFunction.c
=> case change function

Data Structures/LinkedLists/duplicateRemoval.cpp, Tricky Problems/maxOfTwo.cpp
@rathoresrikant  Please review and let me know if any changes required.
=> #413 solved

Algorithms/DynamicProgramming/fibonacci.cpp, Data Structures/LinkedLists/doublyList.cpp, Data Structures/LinkedLists/duplicateRemoval.cpp, Data Structures/LinkedLists/palindrome.cpp
Please review and let me know if any changes required.
=> Issue #325

Geometry Algorithms/inside_polygon_or_not.cpp
This is C++ implementation to check if point inside the polygon or not.
=> coded pragram to check point inside or not

Algorithms/Mathematical Algorithms/max-of-two-numbers.js
=> max of 2 nums

src/c/all_permutations_of_string.c
Created a C Program to print all permutations of a string
=> Created a C Program to print all permutations of a string

Algorithms/anagrams.js
#275 anagrams check in javascript
=> check if two words are anagrams

Algorithms/kaprekar-number-checker.js
issue# 418 kaprekar-number-checker - javascript
=> kaprekar-number-checker

Algorithms/firstNonRepeatingCharacter.php
#266 
Implemented PHP function **findFirstNonRepeatingCharacter**.
=> Find the first non-repeating character in a string - PHP

middle_ll.cpp, nthnodefromend.cpp
Issue #423 Find nth node from end of linked list
=> nth_node_from_end_in_linkedlist

Tricky Problems/swap.py
=> Add swap.py

Data Structures/LinkedLists/sorting.cpp, Tricky Problems/swap.py
=> Add sorting.cpp

Algorithms/Search/binary_search.py
thought would be cool to have this algorithm on python :)
=> binary search iterative on python

src/python/permutationsRecursive.py
Alternative solution to https://github.com/rathoresrikant/HacktoberFestContribute/issues/217 using recursion.
=> Recursive solution in python to print all the permutations of a string

IntToBin.c, Swap.c
Integer to Binary using ra ecursive function.
Swap using bitwise xor.
=> Int to Bin and Swap #457, #456

Algorithms/intToBinary.cpp
Implemented the code to print the binary representation of an integer to solve https://github.com/rathoresrikant/HacktoberFestContribute/issues/457, the program takes the integer as an argument.
=> Added intToBinary.cpp file, this code prints the binary representation of a given integer

convert_string_to_lowercase.cpp
convert string's char to lowercase .
=> convert_string_to_lowercase.cpp

Algorithms/sort_string.cpp
sorting a given string in c++.
=> sort_string.cpp

Algorithms/Array/sorting_array.cpp
=> sorting_array.cpp

Algorithms/swap_without_temp.cpp
=> swap_without_temp.cpp

Tricky Problems/SwapWithoutTempVar.js
#461: Swap numbers without temp variable (Javascript)
=> #461: Swap numbers without temp variable

Algorithms/binaryRepresentation.cpp
added binary representation of a number using c++
=> binary representation of a number

Algorithms/DynamicProgramming/fibonacci_topdown.cpp
Evaluating nth fibonacci number using top down approach.
=> Added fibonacci_topdown.cpp

Algorithms/binary-representation.py
=> Add binary-representation.py

count-occurence.py
=> Add count-occurence.py

Data Structures/Doubly.java, Data Structures/LinkedLists/Middle.java, Data Structures/LinkedLists/Palindrome.java
=> Implementing doubly linked list

Data Structures/Doubly.java, Data Structures/LinkedLists/Middle.java, Data Structures/LinkedLists/Palindrome.java
=> Palindrome to check if a singly linked list is palindrome or not

Data Structures/Doubly.java, Data Structures/LinkedLists/Middle.java, Data Structures/LinkedLists/Palindrome.java
=> Middle Element

StringConcatenator.c
A string concatenator with variable number of arguments using C programming language.
=> I thought it would be nice to add this concatenator here

Algorithms/QuickSort/quicksort.py
A simple quicksort implementation in Python
=> Add a Python implementation of quicksort

Swap.cpp, linked list/Linked_list.c, linked list/Ordered_linked_list.c, linked list/circular_doubly_linked_list.c, linked list/circular_linear_linked_list.c, linked list/doubly_linked_list.c
1.Linked list
2.Circular Linked list
3.Doubly Linked list
4.Circular Doubly Linked list
5.Ordered liked list
=> linked list programs added

MyCode.java, SmallAppofRandom.java, ValidateCreditCard.java
A program who tells the importance of Random function in java coding language.
=> Random.java

decimal to binary conversion (c++)
more decimal numbers can be converted to binary
=> Create decimal to binary conversion (c++)

SeatingA.java
It is basically a problem on which you have to find about all the information of seat no like whether that seat no is window seat no,middle seat no or aisle seat no and you also have to calculate that seat no which will be in front of you or each other....Seat no of train would be starting from lower(1) to upper(6) and then upper(7) to lower(12) and so on...that's the problem!!
=> SeatingA.java

Palinas.cpp
This is the code to check if a given singly-linked list is Palindrome or not.
=> fixes #381

Graph Theory/lca.cpp
=> Added lowest common ancestor algorithm on graph

Algorithms/Mathematical Algorithms/EulerTotient.cpp
counts the number of integers between 1 and n, which are coprime to n
=> Euler Totient function

Algorithms/Mathematical Algorithms/LinearSieve.cpp
computes first n prime numbers in linear time
=> Linear Sieve

maxandminof2numbers.php
Php code to generate the max and min of 2 numbers
=> maxof2numbers

Algorithms/Array/zeroMover.py
This solves Issue #570 in Python.
=> Issue #570 - Move all zeroes to the end of an array

Data Structures/Stacks/perm_identity Reverse_stack_recursion.py
This code is for open issue Reverse a stack using recursion
=> Create perm_identity Reverse_stack_recursion.py

Algorithms/Array/remove-zeroes-then-append.js
Solution for https://github.com/rathoresrikant/HacktoberFestContribute/issues/570 in JavaScript.
=> feat: Array - JS - remove zeroes from an array then append them

HacktoberFestContribute/Algorithms/Mathematical Algorithms/catalan.java
=> Add catalan numbers

Algorithms/Array/element-occurrences.js
Solution for https://github.com/rathoresrikant/HacktoberFestContribute/issues/483 in JavaScript.
=> feat: Array - JS - Find number of times an element occurs in a sorted array

Algorithms/Strings/switch-case.js
Alternative solution for https://github.com/rathoresrikant/HacktoberFestContribute/issues/196 in JavaScript.
=> feat: Strings - JS - Convert lowercase to upper and vice-versa

Unsorted Language-specific Implementations/c-plus-plus/move-all-zeros-to-end-of-array.cpp
I have added new File named move-all-zeros-to-end-of-array.cpp,
please review it
=> Resolved Issue  #570 Move all zeroes to the end of an array.

Unsorted Language-specific Implementations/c/string_reverse.c, Unsorted Language-specific Implementations/c/string_reverse.cpp
=> #576 Added String reverse in c++ using stl stack

code to find fibonacci series
it is a code to find fibonacci series upto n number of terms
=> code to find fibonacci series

C CODE.txt
=> This C code will be useful

Fre.java
=> Number of occurences

Product.py
i have sorted the array and printed highest numbers
=> two numbers with highest product

HacktoberFestContribute/Algorithms/Mathematical Algorithms/factorial.py
Added a recursive algorithm and updated the code to check more efficiently for errors.
=> Added a recursive algorithm

count.py
find the number of times an element occurs in an array
=> count the instances of an element

swap_case.c
#196 in C and in one line
swap_case take a malloced string and return it with swapped case
=> Added #196 in C, in one line

Algorithms/Array/perfect_sum_problem.cpp
Added C++ program for the algorithm in which given an array of integers and a sum, the task is to print all subsets of given array with sum equal to given sum .
-   My pull request has a descriptive title (not a vague title like Update index.md)
-   My pull request targets the master branch of HacktoberFestContribute.
-   None of my changes are plagiarized from another source without proper attribution.
-   My article does not contain shortened URLs or affiliate links.
=> Add perfect_sum_problem to the algorithms folder under cpp category

convert_string_to_lowercase.cpp
=> changes in writing of codes

nested_sum.py, recursive_fibo.py
Calculates sum of elements of a nested list using recursion.
=> nested_sum.py

Algorithms/Mathematical Algorithms/primecheck.py
A very efficient way to check if a entered number is prime or not.
=> Create a prime number checker

Tricky Problems/maxOfTwo.cpp
Simpler function than used for identifying max.
Also added function for identifying min of 2 numbers.
=> Updated file with simpler solution

Algorithms/DynamicProgramming/longest_repeating_subsequence.py
=> Longest Repeating Subsequence

large-factorial.c
to calculate factorials that go out of range. Large Factorials.
=> created large-factorial.c

findmax.py, print.py, pull3.py
converting given integer number to binary
=> integer to binary

reverseStack.java
=> Added the reverse stack functionality

deleteMiddleStackElement.java
=> Added the delete functionality

Algorithms/checkPrime.cpp, Algorithms/checkPrime.py
O(sqrt(n)) python implementation of basic prime number checker
=> Prime Number Checker (Python)

Algorithms/checkPrime.cpp
Checks if user inputted number is Prime or not.
Supports unsigned long long and is O(sqrt(n)) complexity
=> O(sqrt(n)) Prime Number Checker

HacktoberFestContribute/linked list/Multiple_Linked_List.cpp
Added Creation and Display of Multiple List in c.
=> Added Creation and Display of Multiple List in c

Algorithms/Math/calcpi.c, Bit Manipulation/hex2binary.c
Small command line tool for calculating Pi recursively in C
Another tool for printing out Hex as Binary without using %x
=> Calculate Pi Recursively and Bitshift Hex to Boolean without %x

Delete_middle_element_ll.cpp, ds/BST/bst1.h, ds/BST/bst2.h, ds/BinaryTrees/binarytree.h, ds/DP/allways.cpp, ds/DP/coin_tower.cpp, ds/DP/count1ton.cpp, ds/DP/denomination.cpp, ds/DP/editDistance.cpp, ds/DP/knapsack.cpp, ds/DP/lcs.cpp, ds/DP/loot.cpp, ds/DP/matrix_multiplication.cpp, ds/DP/mincost.cpp, ds/DP/mincount.cpp, ds/GenericTrees/treefunctions.h, ds/GenericTrees/treenode.h, ds/Graphs/graph.h, ds/LinkedList/bubblesortll.cpp, ds/LinkedList/llmergesort.cpp, ds/LinkedList/node.cpp, ds/LinkedList/swap.cpp, ds/Priority Queues/minheap.h, ds/Stack and Queue/queuearr.h, ds/Stack and Queue/queuell.h, ds/Stack and Queue/reversestack.cpp, ds/Stack and Queue/stackarr.h, ds/Stack and Queue/stackll.h, ds/Tries and Huffman Codes/trie.cpp
THe data structure folder contains codes of all main data structures like linked lists, stacks, queues, trees,BSTs, binary trees, generic trees, graphs, priority queues, tries and the main questions of DP
=> Data structure folder added

Algorithms/Array/moveZero.hs
This solves Issue #570 in Haskell.
=> Add Haskell code to Issue #570

alphabets.cpp
https://www.geeksforgeeks.org/given-sorted-dictionary-find-precedence-characters/
My solution
=> find alphabets from alien dictionary

Algorithms/Array/Move Zeroes to The End.cpp, Algorithms/MaxPro.cpp
This is the code in C++ to "Move The Zeroes Of An Array to the End".
=> Move Zeroes of Array

HacktoberFestContribute/move_all_zeros_to_array_end.py
Fixed Iuuse #570 . Python code
=> Added Python code to move zeros to array end

Algorithms/reverse.js
used javascript to reverse a string
=> solved the reverse string challange

Algorithms/Mathematical Algorithms/perfect-number.c, Data Structures/Stacks/string_reverse.cpp
This is in response to the issue #576 .
I created a really simple C program which uses stack to reverse an user given string.
=> Added a C program to reverse string

CompeteShell.java, TelevisionWork.java
This is the small application for the working of television like how remote works in a television.
=> TelevisionWork.java

Algorithms/Array/findDoubleArray.cpp
Finds a value in an array. C++
=> Add search algorithm

Data Structures/LinkedLists/LinkedListLength.py
=> Add LinkedListLength.py

find.nth.fibonacci.number
=> Python code to find nth fibonacci number

rev_stack.c
code for reversing a string with stack in c
=> reverse string using stack in c

Reverse.string.python
Reversing string by stack by using python
=> Reversing string by stack

qualifier.py
Snackdown 2019 is coming! There are two rounds (round A and round B) after the qualification round. From both of them, teams can qualify to the pre-elimination round. According to the rules, in each of these two rounds, teams are sorted in descending order by their score and each team with a score greater or equal to the score of the team at the 
K=1500
K=1500
-th place advances to the pre-elimination round (this means it is possible to have more than 
K
K
qualified teams from each round in the case of one or more ties after the 
K
K
-th place).
Today, the organizers ask you to count the number of teams which would qualify for the pre-elimination round from round A for a given value of 
K
K
(possibly different from 
1500
1500
). They provided the scores of all teams to you; you should …
=> qualifier.py

Algorithms/DynamicProgramming/catalan_number.cpp
Dynamic Programming Based Solution (O(n^2) time complexity)
=> Added a C++ Program to Find nth Catalan Number

Algorithms/DynamicProgramming/catalan_ronika.py, Algorithms/Mathematical Algorithms/catalan_ronika.py
Fixes Issue #755 
Language chosen : Python
=> Program to find nth Catalan numbers

Algorithms/Divide and Conquer/ternary-search.cpp
Made in C++, has both recursive and iterative versions, also counts iterations took.
=> Created file to store ternary search.

DeleteVowels.cpp, SumOfPower.cpp
changed the name for ease of access
=> changed name of file from vinay to DeleteVowels

Data Structures/Stack/stringReverse.py, NewmanConwaySeqDP.cpp, newmanConwaySeq.cpp, pernicios.cpp, pernicious.cpp
Added string reversal in python.
=> Added string reversal using stack in python

create_circular_linked_list.cpp, swap_case.py
interchange the case of the letters of input string (issue #196) in python
=> created swapcase.py

print_25_pernicious_num.cpp
added a cpp file to print 25 pernicious numbers using bit manipulation using of inbuilt function "__builtin_popcount()"
=> Created print_25_pernicious_num.cpp

Algorithms/DynamicProgramming/LongestIncreasingSubsequence.cpp
created Longest Increasing Subsequence
=> created Longest Increasing Subsequence

Data Structures/SegmentTrees/Segment Tree lazy propogation.cpp
=> Segment tree range updates with lazy propagation

Data Structures/Heaps/Build Max Heap.cpp
=> Created Build Max Heap

CaseChanging.java
In a string, convert all the lowercase letters to upper case and vice versa.
Solved this challenge in JAVA
=> In a string, convert all the lowercase letters to upper case and vice versa.

CaseChanging.java, src/java/ReverseString.java
Reverse a string using stack. #576
- Solved this challenge
=> Reverse string

NewmanConwaySequence.py
Issue Number #814 
https://github.com/sai-21/HacktoberFestContribute/blob/master/NewmanConwaySequence.py
=> Newman Conway Sequence

LinkedListLengthEvenOdd.cpp, newman_conway_sequence.c
Issue number #814 
https://github.com/Fisiquelaz/HacktoberFestContribute/blob/master/newman_conway_sequence.c
=> Newman-Conway Sequence in C

Algorithms/Mathematical Algorithms/Get-FibonnaciSequence
This script will get the fibonnaci sequence for a provided integer.
=> Created Get-FibonnaciSequence.ps1

Higher_Lower.py
added a file with python code for Higher_Lower
=> Higher_lower.py added

Algorithms/DynamicProgramming/catalan_Adityakumar.cpp, Algorithms/Mathematical Algorithms/catalan_Adityakumar.cpp
Created a Cpp program to find Nth Catalan Number
=> Added Catalan Number in cpp

Data Structures/TrieTree/trie1.cpp
Added different implementation of trie
=> added trie

Algorithms/Palindrome.cpp
its a algorithm in c++ that returns a boolean true is the string received is a palindrome or not
=> Creared a c++ algorithn that checks if a string is a palindrome or not

Algorithms/DynamicProgramming/Gold Mine Problem
Statement - Given a gold mine of n*m dimensions. Each field in this mine contains a positive integer which is the amount of gold in tons. Initially, the miner is at the first column but can be at any row. the miner can move to the cell diagonally up towards the right or right or diagonally down towards the right. Find out the maximum amount of gold he can collect.
=> Create Gold Mine Problem

src/python/zoneRestriction.py
=> zoneRestriction.py

src/python/BalancedTeam.py
Balanced Team solution from Codeforces div 3, question C
=> BalancedTeam.py

1220A.cpp, MARM.cpp
=> OctoberLongChallenge

Algorithms/Graph Theory/APandbridges.cpp, Algorithms/Graph Theory/Kosaraju.cpp, Algorithms/Graph Theory/Prims.cpp, Algorithms/Graph Theory/articulationpoints.cpp, Algorithms/Graph Theory/kruskals.cpp, Algorithms/Graph Theory/topological_sort.cpp
Added new file:   Algorithms/Graph Theory/APandbridges.cpp
Added new file:   Algorithms/Graph Theory/Kosaraju.cpp
Added new file:   Algorithms/Graph Theory/Prims.cpp
Added new file:   Algorithms/Graph Theory/articulationpoints.cpp
Added new file:   Algorithms/Graph Theory/kruskals.cpp
Added new file:   Algorithms/Graph Theory/topological_sort.cpp
=> Added Graph Algorithms(in C++):

fib.cpp, find.nth.fibonacci.number
Allows user to control which term he/she wants to find out
=> Modified program to take user input

StopnWaitProtocol_Demo_Networking
Replace ping system command from code according to your os. sleep for linux/unix and timeout for windows. I put ping because it will work on both the platforms.
=> StopnWaitProtocol.cpp

Algorithms/Strings/KMP_algorithm.cpp
Added my implementation for KMP string matching algorithm in C++.
Please review and merge the changes.
=> Added implementation for KMP algorithm in C++

Data Structures/LinkedLists/Removing duplicates from a sorted linked list.c
inputs should be in a sorted order.
input-1->2->2->3->3->5->NULL
return 1->2->3->NULL
=> removing duplicates from sorted linked list.c

Data Structures/GreatestCommonDivisor(most off).c
Gives the greatest common divisor among two numbers in least amount of time.
=> Create GreatestCommonDivisor(most off).c

HacktoberFestContribute/Algorithms/Bellman-Ford.cpp
=> Bellman-Ford Algorithm code added

oddTp.py
Print odd levels in a Binary Tree initial commit
=> Print odd levels in a Binary Tree

Algorithms/Graph Theory/BipartiteGraph.cpp
Input example:
2
5 3
1 4
2 4
3 5
5 5
2 4
1 4
3 5
4 5
2 5
Output:
Yes
No
=> tell whether graph is bipartite or not

HacktoberFestContribute/Data Structures/Largest_SCC.cpp
Code written for finding size of Largest strongly connected component in a graph.
=> Size of Largest SCC in a graph.

Dynamic Programming/UniquePathsInGrid.cpp
=> Added DP solution to find unique paths in grid

Longest Consecutive Subsequence/solution_O_n2.cpp
=> LOngest COnsecutive Subsequence COde

Algorithms/Array/Moore's Algorithm
An O(n) algorithm for finding element occurring more than n/2 times
can be changed for other frequencies
=> Moore's Algorithm for majority algorithm

Data Structures/Stack/stackll.java
=> stackll.java

Algorithms/Graph Theory/bellman_ford.cpp
This adds Bellman Ford algorithm that computes shortest paths from a single source vertex to all of the other vertices in a weighted digraph. The graph may contain negative weight edges.
Closes #854
=> bellman_ford.cpp: Added Bellman Ford Algorithm

NewmanConvoy_recursion.cs
**Newman-Convoy Program implemented in C# using recursion simply**
=> Added NewmanConvoySequence Program Using Recursion in C#

Algorithms/DynamicProgramming/Catalan-DP_FinalGetsugaa.cs
Catalan Number Program Using Dynamic Programming Approach in C#
=> Added Catalan No Program Using DP in C#

Algorithms/Mathematical Algorithms/Catalan_FinalGetsugaa.cs
Finding Catalan Number Using Recursion Approach in C#
=> Added Catalan Number Program in C#

PushZeroesToEnd.cs
**Program For Pushing Zeroes To End Implemented in C#**
=> Added PushZeroesToEnd Program in C#

sortinglist.cpp
=> Added sortinglist.cpp by Ashwin Khode

SumofLeafNodes.cpp
Implementation of Sum of Leaf Nodes in a Tree using C++. This closes #996
=> SumofLeafNodes.cpp

LinkedList.dart
Dart Implementation of Singly-LinkedList
=> Dart implementation of Singly-LinkedList

Data Structures/LinkedLists/list.cpp
its a basic linked list program in C++ to add entries in a list and print the elements of a linked list
=> Basic linked lists functions
